### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nightblade9**
Add instructions on usage and a sample of how the game will look

### CODE REVIEW

**Comment by nightblade9** [comment]
@paulloz I took some liberties to take a screenshot of my current project (which looks horrible with red-green blindness). Let me know if you want me to take that out or take a screenshot of something else.

Thanks so much for making this!!

**Comment by paulloz** [comment]
Hey! Thanks for the PR, that's awesome. I don't mind at all the screenshot, maybe you can add one with the *protanopia* and/or *tritanopia*?

**Comment by nightblade9** [comment]
That's actually a really good suggestion / oversight on my side. I will definitely add that. 

Plus, I was thinking of adding short GIFs instead (because, technically, you can always test your game with screenshots; but the power of the control is for animation / things with effects/colours/etc.) Do you think that's a good idea?

**Comment by paulloz** [comment]
I actually don't really mind between still or animated frames :)

**Comment by nightblade9** [comment]
@paulloz done, waiting for your feedback once more.

**Comment by paulloz** [comment]
Your link towards [Eman Quest](https://github.com/eman-quest) leads to a
404. Otherwise it's fine for me. Squash your commits once the link is
dealt with and I'll merge right away.

**Comment by nightblade9** [comment]
I haven't squashed commits in ages, and I had to force-push to override my previous commits (I hope I did that correctly). I also removed the link, because it's not really relevant, and added captions to the images.

What do you think?

**Comment by paulloz** [comment]
Lots of thanks!

**Comment by nightblade9** [comment]
No worries. Thanks again for making this plugin (and being patient with the README changes).

**Pull request merged**
